### ISSUE TITLE
createAdminUser

### ISSUE THREAD

**Issue by nixfreak** [ThomasTJdev/nim_tutorials#2]
Getting error "undeclared variable createAdminUser"

Do I need to import nimwc also?

I did find that proc/function in: 

```nimwc-6.0.1/nimwcpkg/databases/_adminusers.nim
18:proc createAdminUser*(db: DbConn) {.discardable.} =
22:  info(createAdminUserMsg.format(anyAdmin.len))

nimwc-6.0.1/nimwcpkg/constants/_strings.nim
139:  createAdminUserMsg* = """
'''

**Comment by nixfreak** [comment]
nm I found it in database_utils

**Comment by ThomasTJdev** [comment]
Please insert the whole error message when compiling and getting an error.

Okay, the error message you are getting is `undeclared variable createAdminUser`. This is Nim telling you, that it cant find `createAdminUser`. You are trying to call it here as a proc: https://github.com/nixfreak/nimweb/blob/89bc2c9faa469f914372f3a3497290360d55e9f4/main.nim#L176-L178

But Nim cant find the proc - that's why it says undeclared.

In my code, you'll find it in the `database_utils.nim` here:
https://github.com/ThomasTJdev/nim_tutorials/blob/501ab3b25299801a2e45bab656aa918fbf3bd7a9/code/nimweb/code/database_utils.nim#L62-L97
